### ISSUE TITLE
Specify a licence

### ISSUE THREAD

**Issue by coderpatros** [MLH/mlh-hackathon-boilerplate#11]
It would be great if there was a licence specified so that I could be sure my usage is permitted and under what conditions.

**Comment by theycallmeswift** [comment]
Hey @patros.  Great catch.  We generally release all of our open source code under the [MIT License](https://opensource.org/licenses/MIT) and content under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).  I've added the MIT license to this repo to reflect this.
